apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: node-app-pipeline
  namespace: ci
spec:
  params:
  - name: repo-url
    type: string
  - name: revision
    type: string
    default: main
  - name: image
    type: string
  - name: node-version
    type: string
    default: "20"
  workspaces:
  - name: shared
  tasks:
  - name: clone
    taskRef:
      resolver: bundles
      params:
      - { name: bundle, value: "registry.registry.svc.cluster.local:5000/tekton/git-clone:v1" }
      - { name: name, value: git-clone }
      - { name: kind, value: task }
    params:
    - { name: url, value: "$(params.repo-url)" }
    - { name: revision, value: "$(params.revision)" }
    workspaces:
    - { name: output, workspace: shared }
  - name: build
    runAfter: [clone]
    taskRef:
      resolver: bundles
      params:
      - { name: bundle, value: "registry.registry.svc.cluster.local:5000/tekton/node-build:v1" }
      - { name: name, value: node-build }
      - { name: kind, value: task }
    params:
    - { name: node-version, value: "$(params.node-version)" }
    - { name: install-command, value: "npm install" }
    workspaces:
    - { name: source, workspace: shared }
  - name: image
    runAfter: [build]
    taskRef:
      resolver: bundles
      params:
      - { name: bundle, value: "registry.registry.svc.cluster.local:5000/tekton/kaniko-build-push:v1" }
      - { name: name, value: kaniko-build-push }
      - { name: kind, value: task }
    params:
    - { name: image, value: "$(params.image)" }
    workspaces:
    - { name: source, workspace: shared }
