apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterResolver.configMapName }}
  namespace: {{ .Values.clusterResolver.namespace }}
data:
  default-namespace: {{ .Values.clusterResolver.defaultNamespace | quote }}
  allowed-namespaces: {{ .Values.clusterResolver.allowedNamespaces | quote }}
